### ISSUE TITLE
Traceback error?

### ISSUE THREAD

**Issue by tab328** [Schlechtwetterfront/xsizetools#10]
I get this error when I try to export something. It is most likely my install or the model, since this error occurred with three versions of ZEtools. Also no textures show up, just the material. Any insight to what the problem is will be appreciated. Thanks in advance.

`
Last 15 log lines:

	INFO (908, do_export): Starting export at 2016-12-08 10:43:51.193000.
	INFO (909, do_export): .msh file path: C:\Users\tab328\Desktop\testing_cube.msh
	INFO (920, do_export): Processing material "Material_001".
	INFO (926, do_export): Finished processing.
	INFO (920, do_export): Processing material "None".
	INFO (926, do_export): Finished processing.
	INFO (33, __exit__): Materials in 0s 165000ms.
	INFO (941, do_export): Processing model "null".
	INFO (33, __exit__): Model in 0s 72000ms.
	INFO (945, do_export): Finished processing.
	INFO (941, do_export): Processing model "Cube".
	INFO (654, convert): Is geometry.
	INFO (33, __exit__): Segments in 0s 2000ms.
	INFO (33, __exit__): Model in 0s 69000ms.
	INFO (33, __exit__): Models in 0s 146000ms.

Traceback:

	Traceback (most recent call last):
	  File "<Script Block >", line 28, in exportbutton_OnClicked
	  File "C:\Users\tab328\Autodesk\Softimage_Mod_Tool_7.5\Addons\xsizetools-1.3.0033\Application\Core\zetexport.py", line 899, in export
	    self.do_export()
	  File "C:\Users\tab328\Autodesk\Softimage_Mod_Tool_7.5\Addons\xsizetools-1.3.0033\Application\Core\zetexport.py", line 944, in do_export
	    self.msh.models.add(conv.convert())
	  File "C:\Users\tab328\Autodesk\Softimage_Mod_Tool_7.5\Addons\xsizetools-1.3.0033\Application\Core\zetexport.py", line 657, in convert
	    self.msh2_model.segments = self.get_segments()
	  File "C:\Users\tab328\Autodesk\Softimage_Mod_Tool_7.5\Addons\xsizetools-1.3.0033\Application\Core\zetexport.py", line 433, in get_segments
	    geometry = self.process_geometry()
	  File "C:\Users\tab328\Autodesk\Softimage_Mod_Tool_7.5\Addons\xsizetools-1.3.0033\Application\Core\zetexport.py", line 405, in process_geometry
	    seg.vertices = self.get_vertices()
	  File "C:\Users\tab328\Autodesk\Softimage_Mod_Tool_7.5\Addons\xsizetools-1.3.0033\Application\Core\zetexport.py", line 250, in get_vertices
	    vert_pos_list = self.export.xsi.CGA_GetNodeVertexPositions(self.geo, True)
	  File "C:\Python26\lib\site-packages\win32comext\axscript\client\pyscript.py", line 105, in __getattr__
	    return getattr(self._scriptItem_.dispatchContainer,attr)
	  File "C:\Python26\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
	    raise AttributeError("%s.%s" % (self._username_, attr))
	AttributeError: Application.CGA_GetNodeVertexPositions
	`

**Comment by Schlechtwetterfront** [comment]
Yes, this is a problem with the install. Did you install the [Visual C++ 2015 redistributable](https://www.visualstudio.com/downloads/#microsoft-visual-c-2015-redistributable-update-3)?
The location on the download page seems to have changed so the description in the install instructions isn't completely correct anymore.

**Comment by tab328** [comment]
Aha! After a couple hours of troubleshooting and answering my own nearly-asked questions, as well as re-reading everyone's instructions, I realized I didn't have the 32 bit version as well. Thanks for your time and help, and of course this invaluable resource! Now to figure out where my textures keep running off to...

**Comment by Schlechtwetterfront** [comment]
I'm glad you got it fixed.

If you have any other problems feel free to open another ticket or post on the [Gametoast Forums](http://gametoast.com/viewtopic.php?f=36&t=26664).
